# Use an official Node.js runtime as a parent image
FROM node:12

# Set the working directory to /app

# Copy the package.json and package-lock.json files to the container
COPY . . 

# Install dependencies
RUN npm install

# Copy the server.js file to the contai

# Expose port 80
RUN npm build
# Start the Node.js application
CMD [ "npm", "start" ]

